flapparams:
  triplength: 365
  flightsintrip: 50
  flightinterval: 1
modelparams:
  workingfolder: /home/spencerthehalfwit/working
  datafolder: /home/spencerthehalfwit/flapdata
  dtalgo: average
  trialdays: 100
  daystorun: 2000
  totaltravellers: 1000
  botspecs:
  - planprobability: 0.01
    weight: 1
  - planprobability: 0.001
    weight: 9
  triplengths:
  - 1
  - 2
  - 3
  - 5
  - 7
  - 7
  - 7
  - 7
  - 14
  - 14
  - 14
  - 14
  - 28
  startday: 0
  dailytotalfactor: 0.9995
  reportdaydelta: 100
