flapparams:
  triplength: 365
  flightsintrip: 50
  flightinterval: 1
  promisesalgo: 1
  promisesmaxpoints: 100
  promisesmaxdays: 10
modelparams:
  loglevel: 3
  workingfolder: ./working
  datafolder: ./data
  dtalgo: average
  trialdays: 10
  daystorun: 100
  totaltravellers: 1
  botspecs:
  - planprobability: 1.0
    weight: 1
  triplengths:
  - 2
  startday: 0
  dailytotalfactor: 0.99
  deterministic: true
