flapparams:
  triplength: 365
  flightsintrip: 50
  flightinterval: 1
  promises:
    algo: 1
    maxpoints: 100
    maxdays: 10
  threads: 2
modelparams:
  loglevel: 3
  workingfolder: ./working
  datafolder: ./data
  dtalgo: average
  trialdays: 10
  daystorun: 100
  totaltravellers: 1
  botspecs:
  - planprobability: 1.0
    weight: 1
  triplengths:
  - 2
  startday: "2021-01-01T00:00:00Z"
  dailytotalfactor: 0.99
  deterministic: false
  threads: 2
